/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basic.demo.jr;

import java.util.Random;
import java.util.Scanner;
import java.io.File;
import java.util.ArrayList;

public class App {
    private Random rand;
    private Scanner scan;
    private String nameCheck;
    private int chooser;
    private ArrayList<String> names;
    private ArrayList<String> originalList;

    //Sets up the foundations for the ArrayList<String> that will be called "names"
    public App(){
        scan = new Scanner (System.in);
        rand = new Random();

        originalList = new ArrayList<String>();
        names = new ArrayList<String>();
        nameCheck = "";
        chooser = 0;
    }

    public static void main(String[] arg) {        
        App app = new App();
        
        //----------------------------------------------------------------------------//
        //This lets the user input in each name
        // boolean answer = app.setList();
        // if (answer){
        //     System.out.println("The name that has been chosen is " + app.getName());
        // }
        //----------------------------------------------------------------------------//
        
        //This gets the names from a text file
        app.readFile("nameList.txt");
        app.copyOriginalList();

        //----------------------------------------------------------------------------//
        //This prints out one name individually
        //System.out.println("The name that has been chosen is " + app.getName());
        //----------------------------------------------------------------------------//

        //This way prints out all the names in the list in a random order
        app.printNames();
        System.out.println("----");
        app.randomizeNames();
        app.printNames();

    }

    //This method makes the list of names
    public boolean setList(){
         //Gives the user chance to choose how many names will go into the ArrayList
        System.out.println("How many names would you like to input? (Insert as digits)");
        int people = scan.nextInt();
        if (people < 1){
            System.out.println("OK then, goodbye");
            return false;
        }
        scan.nextLine();
        //Here the user will input all the names
        for(int j = 0; j < people; j++){
            if (j == 0){
                System.out.println("Please insert the first name");
            }    
            else{
                System.out.println("Please insert another name");
            }
            nameCheck = scan.nextLine();
            if (nameCheck == ""){
                System.out.println("A name has not been entered.");
                j--;
            }
            else{
                names.add(nameCheck);
            }
        }
        return true;
    }
    //This method chooses a random name from the ArrayLIst
    public String getName(){
        chooser = names.size();
        return names.get(rand.nextInt(chooser));
    }



    //Separates Part 2




    public void readFile(String file){
        try{
            Scanner input = new Scanner (new File(file));

            while (input.hasNextLine()) {
                String line = input.nextLine();
                names.add(line);
            }
            input.close();

        }   catch (Exception ex) {
                ex.printStackTrace();
        }
    }
    
    public void copyOriginalList(){
        for(String name : names) {
            originalList.add(name);
        }
    }

    public void printNames() {
        for(String name : names) {
            System.out.println(name);
        }
    }

    public void randomizeNames(){
        for(int j = 0; j < names.size(); j++){
            swapNames(j, rand.nextInt(names.size()));
        }
    }

    public void swapNames (int source, int destination){
        String swapee = names.get(destination);
        String swapper = names.get(source);
        names.set(destination, swapper);
        names.set(source, swapee);
    }
}
